- hosts:
    harvesters

  vars_files:
    - vars_docker.yaml

  vars:
    pip:
      executable: pip3
      apt_package: python3-pip
      packages:
        # - tweepy
        - nltk
        - fiona
        - sklearn
        - textblob
        - couchdb
        - pickle-mixin
        # - shapely
        # - mpcouch
  
    git_repo: https://github.com/myang29/COMP90024-Assign2.git
    git_folder: "{{ mount_point.symlink }}/COMP90024-Assign2"
    result_folder: "{{ mount_point.symlink }}/result"
    remote_ip: http://[IP address of the database instance]:9024

  tasks:
    - name: "Make sure git and {{ pip.executable }} are installed"
      become: true
      apt:
        name: 
          - git
          - "{{ pip.apt_package }}"
        state: latest
        update_cache: yes

    - name: Use {{ pip.executable }} to install {{ pip.packages }}
      pip:
        executable: "{{ pip.executable }}"
        name: "{{ pip.packages }}"
        state: present

    - name: Manually install tweepy
      shell: "{{ pip.executable }} install tweepy"

    - name: Create folder {{ result_folder }} for harvester result
      become: true
      file:
        state: directory
        path: "{{ result_folder }}"
        owner: "{{ mount_point.owner }}"
        group: "{{ mount_point.group }}"

    - name: Create folder {{ git_folder }} for git repository
      become: true
      file:
        state: directory
        path: "{{ git_folder }}"
        owner: "{{ mount_point.owner }}"
        group: "{{ mount_point.group }}"

    - name: Clone git repository to {{ git_folder }}
      git:
        repo: "{{ git_repo }}"
        dest: "{{ git_folder }}"


    - name: Run harvester and sentiment analysis application
      shell: |
          cd {{ git_folder }}/harvester
          nohup python3 ./harvester.py {{ result_folder }}/ {{ remote_ip }} &
      register: python3_out

    - debug:
        msg: "{{ python3_out }}"