# mymsg: hello

docker_dependencies: ["docker"]

docker_daemon:
  folder: /etc/systemd/system/docker.service.d
  http_file: /etc/systemd/system/docker.service.d/http-proxy.conf
  http_line: |
    [Service]
    Environment="HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000" "NO_PROXY=localhost,127.0.0.1,127.0.1.1,ubuntu"
  https_file: /etc/systemd/system/docker.service.d/https-proxy.conf
  https_line: |
    [Service]
    Environment="HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000" "NO_PROXY=localhost,127.0.0.1,127.0.1.1,ubuntu"

mount_point: 
  path: /data
  owner: ubuntu
  group: ubuntu
  symlink: /home/ubuntu/data      

couchdb:
  image: apache/couchdb:2.3.1
  container: couchSingleton
  path: "{{ mount_point.symlink }}/couchdb"
  # config_volume: couchdb_etc
  owner: ubuntu
  group: ubuntu
  port: 9024

nginx:
  image: nginx
  container: nginxServer
  path: "{{ mount_point.symlink }}/nginxServer"


# -v {{ couchdb.config_volume }}:/opt/couchdb/etc
docker_command:
  pull: "docker pull {{ couchdb.image }}"
  run: > 
    docker run --name {{ couchdb.container }}
    -v {{ couchdb.path }}:/opt/couchdb/data
    -p {{ couchdb.port }}:5984
    -d {{ couchdb.image }}
  start: "docker start {{ couchdb.container }}"
      