- name: Create volume(s) on UoMCloud -pilot
  os_volume:
    display_name: '{{ item.vol_name }}'
    size: '{{ item.vol_size }}'
    availability_zone: '{{ availability_zone }}'
    wait: yes
    timeout: 200
    state: present
  loop: '{{ instance_pilot }}'
  register: os_vol

- name: Create a list of volume Ids -pilot
  set_fact:
    os_vol_ids: '{{ os_vol_ids|default([]) + [ item.id ] }}'
  loop: '{{ os_vol.results }}'

- debug:
    msg: "Volume(s) {{ os_vol_ids }} created."

