- name: Install pip
  become: yes
  apt:
    name: ['python-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install openstacksdk
  become: yes
  pip:
    executable: pip
    name: ['openstacksdk']
    state: latest

